### ISSUE TITLE
limit on API

### ISSUE THREAD

**Issue by uxkjaer** [ui5-community/bestofui5-website#80]
Hello,

Sorry for the mess on the actions. I've been trying to get this running. But for some reason the github token is blank for me and I'm exhausting the limits. Not sure if this is because i'm not the owner of the repo?

**Comment by marianfoo** [comment]
no worries,
i remembered yesterday too that we need to give the GitHub token to the workflow
So, your change should work
I'll have a look

**Comment by marianfoo** [comment]
i cleaned up a little bit https://github.com/ui5-community/ui5-community.github.io/commit/9e7a6cc778c87a9289b4ba8b6cfd25e41dc53a4c
The workflow works now but not the jsdoc anymore, need to have a look later.
It was intentional that the requests are just processed one after the other so that you don't hit rate limits that quickly.
Currently crawl takes about 40-60 seconds and thats quiet ok for now.
I thought about seperating crawl/build (#25 ), but was hoping rate limits are still far away.
If we push few times a day, we might hit that.

**Comment by uxkjaer** [comment]
Thanks for your inputs, i've sorted out the error on the jsdoc object. The API is working now.

**Comment by marianfoo** [comment]
perfect
fyi: the latest data.json is always on the docs branch
i try to keep the data.json in main as current as possible
